/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StaffIndexRouteImport } from './routes/staff.index'
import { Route as StaffVideosRouteImport } from './routes/staff.videos'
import { Route as StaffStaffRouteImport } from './routes/staff.staff'
import { Route as StaffServicesRouteImport } from './routes/staff.services'
import { Route as StaffJobsRouteImport } from './routes/staff.jobs'
import { Route as StaffEnquiriesRouteImport } from './routes/staff.enquiries'
import { Route as StaffCustomersRouteImport } from './routes/staff.customers'
import { Route as StaffBalancesRouteImport } from './routes/staff.balances'
import { Route as AppServicesRouteImport } from './routes/app.services'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppPaymentsRouteImport } from './routes/app.payments'
import { Route as AppHistoryRouteImport } from './routes/app.history'
import { Route as AppFeedbackRouteImport } from './routes/app.feedback'
import { Route as AppContactRouteImport } from './routes/app.contact'
import { Route as AppServicesNewRouteImport } from './routes/app.services.new'

const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffRoute,
} as any)
const StaffVideosRoute = StaffVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => StaffRoute,
} as any)
const StaffStaffRoute = StaffStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => StaffRoute,
} as any)
const StaffServicesRoute = StaffServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => StaffRoute,
} as any)
const StaffJobsRoute = StaffJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => StaffRoute,
} as any)
const StaffEnquiriesRoute = StaffEnquiriesRouteImport.update({
  id: '/enquiries',
  path: '/enquiries',
  getParentRoute: () => StaffRoute,
} as any)
const StaffCustomersRoute = StaffCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => StaffRoute,
} as any)
const StaffBalancesRoute = StaffBalancesRouteImport.update({
  id: '/balances',
  path: '/balances',
  getParentRoute: () => StaffRoute,
} as any)
const AppServicesRoute = AppServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsRoute = AppPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedbackRoute = AppFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AppRoute,
} as any)
const AppContactRoute = AppContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => AppRoute,
} as any)
const AppServicesNewRoute = AppServicesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppServicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/staff': typeof StaffRouteWithChildren
  '/app/contact': typeof AppContactRoute
  '/app/feedback': typeof AppFeedbackRoute
  '/app/history': typeof AppHistoryRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/services': typeof AppServicesRouteWithChildren
  '/staff/balances': typeof StaffBalancesRoute
  '/staff/customers': typeof StaffCustomersRoute
  '/staff/enquiries': typeof StaffEnquiriesRoute
  '/staff/jobs': typeof StaffJobsRoute
  '/staff/services': typeof StaffServicesRoute
  '/staff/staff': typeof StaffStaffRoute
  '/staff/videos': typeof StaffVideosRoute
  '/staff/': typeof StaffIndexRoute
  '/app/services/new': typeof AppServicesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/contact': typeof AppContactRoute
  '/app/feedback': typeof AppFeedbackRoute
  '/app/history': typeof AppHistoryRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/services': typeof AppServicesRouteWithChildren
  '/staff/balances': typeof StaffBalancesRoute
  '/staff/customers': typeof StaffCustomersRoute
  '/staff/enquiries': typeof StaffEnquiriesRoute
  '/staff/jobs': typeof StaffJobsRoute
  '/staff/services': typeof StaffServicesRoute
  '/staff/staff': typeof StaffStaffRoute
  '/staff/videos': typeof StaffVideosRoute
  '/staff': typeof StaffIndexRoute
  '/app/services/new': typeof AppServicesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/staff': typeof StaffRouteWithChildren
  '/app/contact': typeof AppContactRoute
  '/app/feedback': typeof AppFeedbackRoute
  '/app/history': typeof AppHistoryRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/services': typeof AppServicesRouteWithChildren
  '/staff/balances': typeof StaffBalancesRoute
  '/staff/customers': typeof StaffCustomersRoute
  '/staff/enquiries': typeof StaffEnquiriesRoute
  '/staff/jobs': typeof StaffJobsRoute
  '/staff/services': typeof StaffServicesRoute
  '/staff/staff': typeof StaffStaffRoute
  '/staff/videos': typeof StaffVideosRoute
  '/staff/': typeof StaffIndexRoute
  '/app/services/new': typeof AppServicesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/staff'
    | '/app/contact'
    | '/app/feedback'
    | '/app/history'
    | '/app/payments'
    | '/app/profile'
    | '/app/services'
    | '/staff/balances'
    | '/staff/customers'
    | '/staff/enquiries'
    | '/staff/jobs'
    | '/staff/services'
    | '/staff/staff'
    | '/staff/videos'
    | '/staff/'
    | '/app/services/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/auth'
    | '/app/contact'
    | '/app/feedback'
    | '/app/history'
    | '/app/payments'
    | '/app/profile'
    | '/app/services'
    | '/staff/balances'
    | '/staff/customers'
    | '/staff/enquiries'
    | '/staff/jobs'
    | '/staff/services'
    | '/staff/staff'
    | '/staff/videos'
    | '/staff'
    | '/app/services/new'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/staff'
    | '/app/contact'
    | '/app/feedback'
    | '/app/history'
    | '/app/payments'
    | '/app/profile'
    | '/app/services'
    | '/staff/balances'
    | '/staff/customers'
    | '/staff/enquiries'
    | '/staff/jobs'
    | '/staff/services'
    | '/staff/staff'
    | '/staff/videos'
    | '/staff/'
    | '/app/services/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  StaffRoute: typeof StaffRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/videos': {
      id: '/staff/videos'
      path: '/videos'
      fullPath: '/staff/videos'
      preLoaderRoute: typeof StaffVideosRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/staff': {
      id: '/staff/staff'
      path: '/staff'
      fullPath: '/staff/staff'
      preLoaderRoute: typeof StaffStaffRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/services': {
      id: '/staff/services'
      path: '/services'
      fullPath: '/staff/services'
      preLoaderRoute: typeof StaffServicesRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/jobs': {
      id: '/staff/jobs'
      path: '/jobs'
      fullPath: '/staff/jobs'
      preLoaderRoute: typeof StaffJobsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/enquiries': {
      id: '/staff/enquiries'
      path: '/enquiries'
      fullPath: '/staff/enquiries'
      preLoaderRoute: typeof StaffEnquiriesRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/customers': {
      id: '/staff/customers'
      path: '/customers'
      fullPath: '/staff/customers'
      preLoaderRoute: typeof StaffCustomersRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/balances': {
      id: '/staff/balances'
      path: '/balances'
      fullPath: '/staff/balances'
      preLoaderRoute: typeof StaffBalancesRouteImport
      parentRoute: typeof StaffRoute
    }
    '/app/services': {
      id: '/app/services'
      path: '/services'
      fullPath: '/app/services'
      preLoaderRoute: typeof AppServicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/payments': {
      id: '/app/payments'
      path: '/payments'
      fullPath: '/app/payments'
      preLoaderRoute: typeof AppPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/history': {
      id: '/app/history'
      path: '/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/feedback': {
      id: '/app/feedback'
      path: '/feedback'
      fullPath: '/app/feedback'
      preLoaderRoute: typeof AppFeedbackRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/contact': {
      id: '/app/contact'
      path: '/contact'
      fullPath: '/app/contact'
      preLoaderRoute: typeof AppContactRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/services/new': {
      id: '/app/services/new'
      path: '/new'
      fullPath: '/app/services/new'
      preLoaderRoute: typeof AppServicesNewRouteImport
      parentRoute: typeof AppServicesRoute
    }
  }
}

interface AppServicesRouteChildren {
  AppServicesNewRoute: typeof AppServicesNewRoute
}

const AppServicesRouteChildren: AppServicesRouteChildren = {
  AppServicesNewRoute: AppServicesNewRoute,
}

const AppServicesRouteWithChildren = AppServicesRoute._addFileChildren(
  AppServicesRouteChildren,
)

interface AppRouteChildren {
  AppContactRoute: typeof AppContactRoute
  AppFeedbackRoute: typeof AppFeedbackRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppPaymentsRoute: typeof AppPaymentsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppServicesRoute: typeof AppServicesRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppContactRoute: AppContactRoute,
  AppFeedbackRoute: AppFeedbackRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppPaymentsRoute: AppPaymentsRoute,
  AppProfileRoute: AppProfileRoute,
  AppServicesRoute: AppServicesRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface StaffRouteChildren {
  StaffBalancesRoute: typeof StaffBalancesRoute
  StaffCustomersRoute: typeof StaffCustomersRoute
  StaffEnquiriesRoute: typeof StaffEnquiriesRoute
  StaffJobsRoute: typeof StaffJobsRoute
  StaffServicesRoute: typeof StaffServicesRoute
  StaffStaffRoute: typeof StaffStaffRoute
  StaffVideosRoute: typeof StaffVideosRoute
  StaffIndexRoute: typeof StaffIndexRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffBalancesRoute: StaffBalancesRoute,
  StaffCustomersRoute: StaffCustomersRoute,
  StaffEnquiriesRoute: StaffEnquiriesRoute,
  StaffJobsRoute: StaffJobsRoute,
  StaffServicesRoute: StaffServicesRoute,
  StaffStaffRoute: StaffStaffRoute,
  StaffVideosRoute: StaffVideosRoute,
  StaffIndexRoute: StaffIndexRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  StaffRoute: StaffRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
